he

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -27,17 +27,22 @@ jobs:
       - name: Checkout the source code
         uses: actions/checkout@v4
 
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Clear Docker Cache
+        run: docker builder prune -f
+
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      - name: Get Existing Image Digest
+        id: image-digest-before
+        run: |
+          echo "digest=$(docker buildx imagetools inspect lalitpatidar001/pet-adoption-backend:latest --format '{{ .Digest }}')" >> $GITHUB_ENV
 
       - name: Build and Push
         uses: docker/build-push-action@v6
@@ -59,9 +64,19 @@ jobs:
             "GOOGLE_AUTH_CLIENT_SECRET=${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}"
             "GOOGLE_AUTH_CALLBACK_URL=${{ secrets.GOOGLE_AUTH_CALLBACK_URL }}"
 
-      - name: Verify Image Push
+      - name: Get New Image Digest
+        id: image-digest-after
         run: |
-          docker buildx imagetools inspect lalitpatidar001/pet-adoption-backend:latest
+          echo "digest=$(docker buildx imagetools inspect lalitpatidar001/pet-adoption-backend:latest --format '{{ .Digest }}')" >> $GITHUB_ENV
+
+      - name: Check Image Push Success
+        run: |
+          if [ "${{ env.digest_before }}" = "${{ env.digest_after }}" ]; then
+            echo "Image push failed or image unchanged."
+            exit 1
+          else
+            echo "Image pushed successfully."
+          fi
 
   deploy:
     needs: build
